
import "./globals.css";
import Header from "@/components/Header";
import ProductProvider from "@/context/ProductContext";
import UIProvider from '@/context/UIContext'
import { AuthProvider } from "@/context/AuthContext";
import { WishlistProvider } from "@/context/WishlistContext";
import Footer from "@/components/footer";
import CartProvider from "@/context/CartContext";
import Basket from "@/components/basket";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CartProvider>
        <WishlistProvider>
          <AuthProvider>
            <UIProvider>
              <ProductProvider>
                <body>
                  <Header />
                  <Basket/>
                  <main>{children}</main>
                  <Footer />
                </body>
              </ProductProvider>
            </UIProvider>
          </AuthProvider>
        </WishlistProvider>
      </CartProvider>
    </html>
  );
}
